[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.147.7"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    buildDir = "public"
    baseUrl = "https://quintana-abogados.com"

[context.deploy-preview]
  command = "hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"

[[redirects]]
  from = "https://main--quintana-abogados.netlify.app/*"
  to = "https://quintana-abogados.com/:splat"
  status = 301
  force = true